In [1]:
import pandas as pd
import numpy as np

Cargar dataframe

In [2]:
# Ajustar la configuración para mostrar todas las columnas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
empresas_csv = r'C:\Users\alexa\OneDrive\Escritorio\Bases_Data\inec\EMPRESAS2023_periodo_2023.csv'
raw_inec = pd.read_csv(empresas_csv, delimiter=';')

C:\Users\alexa\AppData\Local\Temp\ipykernel_12276\1676626834.py:2: DtypeWarning: Columns (25,28) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_inec = pd.read_csv(empresas_csv, delimiter=';')

In [15]:
# Identificar valores únicos en la columna
print(raw_inec['ventas_nacionales'].unique())
print(raw_inec['ventas_totales'].unique())
print(raw_inec['propietarios_sexo'].unique())

<IntegerArray>
[<NA>]
Length: 1, dtype: Int64
<IntegerArray>
[<NA>]
Length: 1, dtype: Int64
['Hombres' 'Mujeres' ' ']

In [13]:
# Lista de columnas a convertir
columns_to_convert = ['ventas_totales', 'ventas_nacionales', 'exportaciones_netas',
                      'plazas_equiv', 'plazas_equiv_hombres', 'plazas_equiv_mujeres',
                      'plazas', 'plazas_hombres', 'plazas_mujeres', 'plazas_ult']

# Convertir cada columna a numérico y luego a Int64
for column in columns_to_convert:
    raw_inec[column] = pd.to_numeric(raw_inec[column], errors='coerce')
    raw_inec[column] = raw_inec[column].astype('Int64')

# Verificar la conversión
print(raw_inec.dtypes)

id_empresa                       int64
anio                             int64
situacion                       object
forma_institucional             object
unidad_legal_tipo               object
clase_contribuyente             object
obligado_llevar_contabilidad    object
gsectores                       object
codigo_seccion                  object
seccion                         object
codigo_division                 object
division                        object
codigo_clase                    object
clase                           object
zona_planif                     object
codigo_provincia                 int64
provincia                       object
codigo_canton                    int64
canton                          object
ventas_totales                   Int64
ventas_nacionales                Int64
exportaciones_netas              Int64
plazas_equiv                     Int64
plazas_equiv_hombres             Int64
plazas_equiv_mujeres             Int64
plazas                           Int64
plazas_hombres                   Int64
plazas_mujeres                   Int64
plazas_ult                       Int64
plazas_ult_hombres              object
plazas_ult_mujeres              object
plazas_iess_trim_1              object
plazas_iess_trim_2              object
plazas_iess_trim_3              object
plazas_iess_trim_4              object
plazas_rango_edad_1             object
plazas_rango_edad_2             object
plazas_rango_edad_3             object
plazas_rango_edad_4             object
plazas_rango_edad_5             object
plazas_ult_rango_edad_1         object
plazas_ult_rango_edad_2         object
plazas_ult_rango_edad_3         object
plazas_ult_rango_edad_4         object
plazas_ult_rango_edad_5         object
empleo_equiv                    object
empleo_equiv_hombres            object
empleo_equiv_mujeres            object
empleo                          object
empleo_hombres                  object
empleo_mujeres                  object
empleo_ult                      object
empleo_ult_hombres              object
empleo_ult_mujeres              object
empleo_iess_trim_1              object
empleo_iess_trim_2              object
empleo_iess_trim_3              object
empleo_iess_trim_4              object
empleo_rango_edad_1             object
empleo_rango_edad_2             object
empleo_rango_edad_3             object
empleo_rango_edad_4             object
empleo_rango_edad_5             object
empleo_ult_rango_edad_1         object
empleo_ult_rango_edad_2         object
empleo_ult_rango_edad_3         object
empleo_ult_rango_edad_4         object
empleo_ult_rango_edad_5         object
estrato_ventas                  object
estrato_plazase                 object
estrato_empleoe                 object
estrato_plazasp                 object
estrato_empleop                 object
estrato_plazasu                 object
estrato_empleou                 object
estrato_ventas_cop              object
estrato_plazas_cop              object
tamanoe_plazas                  object
tamanoe_empleo                  object
tamanop_plazas                  object
tamanop_empleo                  object
tamanou_plazas                  object
tamanou_empleo                  object
tamano_cop                      object
rimpe                           object
remuneraciones                  object
remuneraciones_hombres          object
remuneraciones_mujeres          object
estructura_estrat               object
propietarios_sexo               object
fecha_inicio_actividad          object
fecha_cese_actividad            object
fecha_reinicio_actividad        object
fecha_inscripcion               object
fecha_actualizacion             object
fecha_suspension_definitiva     object
dtype: object

In [5]:
print(raw_inec.columns)

Index(['id_empresa', 'anio', 'situacion', 'forma_institucional',
       'unidad_legal_tipo', 'clase_contribuyente',
       'obligado_llevar_contabilidad', 'gsectores', 'codigo_seccion',
       'seccion', 'codigo_division', 'division', 'codigo_clase', 'clase',
       'zona_planif', 'codigo_provincia', 'provincia', 'codigo_canton',
       'canton', 'ventas_totales', 'ventas_nacionales', 'exportaciones_netas',
       'plazas_equiv', 'plazas_equiv_hombres', 'plazas_equiv_mujeres',
       'plazas', 'plazas_hombres', 'plazas_mujeres', 'plazas_ult',
       'plazas_ult_hombres', 'plazas_ult_mujeres', 'plazas_iess_trim_1',
       'plazas_iess_trim_2', 'plazas_iess_trim_3', 'plazas_iess_trim_4',
       'plazas_rango_edad_1', 'plazas_rango_edad_2', 'plazas_rango_edad_3',
       'plazas_rango_edad_4', 'plazas_rango_edad_5', 'plazas_ult_rango_edad_1',
       'plazas_ult_rango_edad_2', 'plazas_ult_rango_edad_3',
       'plazas_ult_rango_edad_4', 'plazas_ult_rango_edad_5', 'empleo_equiv',
       'empleo_equiv_hombres', 'empleo_equiv_mujeres', 'empleo',
       'empleo_hombres', 'empleo_mujeres', 'empleo_ult', 'empleo_ult_hombres',
       'empleo_ult_mujeres', 'empleo_iess_trim_1', 'empleo_iess_trim_2',
       'empleo_iess_trim_3', 'empleo_iess_trim_4', 'empleo_rango_edad_1',
       'empleo_rango_edad_2', 'empleo_rango_edad_3', 'empleo_rango_edad_4',
       'empleo_rango_edad_5', 'empleo_ult_rango_edad_1',
       'empleo_ult_rango_edad_2', 'empleo_ult_rango_edad_3',
       'empleo_ult_rango_edad_4', 'empleo_ult_rango_edad_5', 'estrato_ventas',
       'estrato_plazase', 'estrato_empleoe', 'estrato_plazasp',
       'estrato_empleop', 'estrato_plazasu', 'estrato_empleou',
       'estrato_ventas_cop', 'estrato_plazas_cop', 'tamanoe_plazas',
       'tamanoe_empleo', 'tamanop_plazas', 'tamanop_empleo', 'tamanou_plazas',
       'tamanou_empleo', 'tamano_cop', 'rimpe', 'remuneraciones',
       'remuneraciones_hombres', 'remuneraciones_mujeres', 'estructura_estrat',
       'propietarios_sexo', 'fecha_inicio_actividad', 'fecha_cese_actividad',
       'fecha_reinicio_actividad', 'fecha_inscripcion', 'fecha_actualizacion',
       'fecha_suspension_definitiva'],
      dtype='object')

Visualizar df

In [19]:
raw_inec.head()

,id_empresa,anio,situacion,forma_institucional,unidad_legal_tipo,clase_contribuyente,obligado_llevar_contabilidad,gsectores,codigo_seccion,seccion,codigo_division,division,codigo_clase,clase,zona_planif,codigo_provincia,provincia,codigo_canton,canton,ventas_totales,ventas_nacionales,exportaciones_netas,plazas_equiv,plazas_equiv_hombres,plazas_equiv_mujeres,plazas,plazas_hombres,plazas_mujeres,plazas_ult,plazas_ult_hombres,plazas_ult_mujeres,plazas_iess_trim_1,plazas_iess_trim_2,plazas_iess_trim_3,plazas_iess_trim_4,plazas_rango_edad_1,plazas_rango_edad_2,plazas_rango_edad_3,plazas_rango_edad_4,plazas_rango_edad_5,plazas_ult_rango_edad_1,plazas_ult_rango_edad_2,plazas_ult_rango_edad_3,plazas_ult_rango_edad_4,plazas_ult_rango_edad_5,empleo_equiv,empleo_equiv_hombres,empleo_equiv_mujeres,empleo,empleo_hombres,empleo_mujeres,empleo_ult,empleo_ult_hombres,empleo_ult_mujeres,empleo_iess_trim_1,empleo_iess_trim_2,empleo_iess_trim_3,empleo_iess_trim_4,empleo_rango_edad_1,empleo_rango_edad_2,empleo_rango_edad_3,empleo_rango_edad_4,empleo_rango_edad_5,empleo_ult_rango_edad_1,empleo_ult_rango_edad_2,empleo_ult_rango_edad_3,empleo_ult_rango_edad_4,empleo_ult_rango_edad_5,estrato_ventas,estrato_plazase,estrato_empleoe,estrato_plazasp,estrato_empleop,estrato_plazasu,estrato_empleou,estrato_ventas_cop,estrato_plazas_cop,tamanoe_plazas,tamanoe_empleo,tamanop_plazas,tamanop_empleo,tamanou_plazas,tamanou_empleo,tamano_cop,rimpe,remuneraciones,remuneraciones_hombres,remuneraciones_mujeres,estructura_estrat,propietarios_sexo,fecha_inicio_actividad,fecha_cese_actividad,fecha_reinicio_actividad,fecha_inscripcion,fecha_actualizacion,fecha_suspension_definitiva
0,13582468014,2023,Activo,Persona Natural obligado a llevar contabilidad,Persona Natural,Otro Contribuyente,Si,Comercio,G,"Comercio, reparación automotores y motocicletas",G47,"Comercio al por menor, excepto el de vehículos...",G4772,Venta al por menor de productos farmacéuticos ...,"Zona 5 - Santa Elena, Guayas, Los Ríos, Bolíva...",12,Los Ríos,1205,Quevedo,,,,"3,16666666666667","3,16666666666667",,3,3,,3,3,,"3,6667",3,3,3,,1,"1,16666666666667",,1,,1,1,,1,"3,16666666666667","3,16666666666667",,3,3,,3,3,,"3,6667",3,3,3,,1,"1,16666666666667",,1,,1,1,,1,,Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),,Estrato I (<= 9),Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,,"17126,52","17126,52",,Plazas de empleo registrado,Hombres,1974 IV Trimestre,,,1981 IV Trimestre,2020 II Trimestre,
1,13582469011,2023,Activo,Persona Natural no obligado a llevar contabilidad,Persona Natural,Otro Contribuyente,No,Comercio,G,"Comercio, reparación automotores y motocicletas",G47,"Comercio al por menor, excepto el de vehículos...",G4773,Venta al por menor de otros productos nuevos e...,"Zona 6 - Azuay, Cañar, Morona Santiago",3,Cañar,301,Azogues,,,,1,,1,1,,1,1,,1,1,1,1,1,,,,,1,,,,,1,1,,1,1,,1,1,,1,1,1,1,1,,,,,1,,,,,1,,Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),,Estrato I (<= 9),Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,,5400,,5400,Plazas de empleo registrado,Mujeres,1994 II Trimestre,,2000 III Trimestre,1994 III Trimestre,2012 IV Trimestre,2020 IV Trimestre
2,13582477013,2023,Activo,Persona Natural no obligado a llevar contabilidad,Persona Natural,Otro Contribuyente,No,Comercio,G,"Comercio, reparación automotores y motocicletas",G47,"Comercio al por menor, excepto el de vehículos...",G4761,"Venta al por menor de libros, periódicos y art...","Zona 6 - Azuay, Cañar, Morona Santiago",1,Azuay,101,Cuenca,,,,"5,25","1,16666666666667","4,08333333333333",5,1,4,4,1,3,4,4,"8,6667","4,3333",,",833333333333333","2,16666666666667","2,25",,,,2,2,,"5,25","1,16666666666667","4,08333333333333",5,1,4,4,1,3,4,4,"8,6667","4,3333",,",833333333333333","2,16666666666667","2,25",,,,2,2,,Estrato II (100.001 – 1.000.000),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato II (300.001 – 1.000.000),Estrato I (<= 9),Pequeña empresa,Pequeña empresa,Pequeña empresa,Pequeña empresa,Pequeña empresa,Pequeña empresa,Pequeña empresa,Emprendedor,"31084,58","6415,02","24669,56",Ventas y plazas de empleo registrado actividad...,Hombres,1980 I Trimestre,,,1981 IV Trimestre,2023 II Trimestre,
3,13582478010,2023,Activo,Persona Natural no obligado a llevar contabilidad,Persona Natural,Rimpe,No,Comercio,G,"Comercio, reparación automotores y motocicletas",G47,"Comercio al por menor, excepto el de vehículos...",G4771,"Venta al por menor de prendas de vestir, calza...","Zona 6 - Azuay, Cañar, Morona Santiago",1,Azuay,101,Cuenca,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Estrato I (<= 100.000),,,,,,,Estrato I (<= 300.000),,Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,Negocio Popular,,,,RIMPE 2022,Hombres,1970 I Trimestre,,,1981 IV Trimestre,2017 III Trimestre,
4,13582485016,2023,Activo,Persona Natural no obligado a llevar contabilidad,Persona Natural,Otro Contribuyente,No,Industrias Manufactureras,C,Industrias manufactureras,C25,"Fabricación de productos elaborados de metal, ...",C2511,Fabricación de productos metálicos para uso es...,"Zona 6 - Azuay, Cañar, Morona Santiago",1,Azuay,101,Cuenca,,,,1,1,,1,1,,1,1,,1,1,1,1,,,,1,,,,,1,,1,1,,1,1,,1,1,,1,1,1,1,,,,1,,,,,1,,Estrato I (<= 100.000),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 9),Estrato I (<= 300.000),Estrato I (<= 9),Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,Microempresa,Negocio Popular,5400,5400,,Plazas de empleo registrado,Hombres,1978 I Trimestre,,1998 III Trimestre,1981 IV Trimestre,2016 IV Trimestre,1981 IV Trimestre

In [9]:
raw_inec.dtypes

id_empresa                       int64
anio                             int64
situacion                       object
forma_institucional             object
unidad_legal_tipo               object
clase_contribuyente             object
obligado_llevar_contabilidad    object
gsectores                       object
codigo_seccion                  object
seccion                         object
codigo_division                 object
division                        object
codigo_clase                    object
clase                           object
zona_planif                     object
codigo_provincia                 int64
provincia                       object
codigo_canton                    int64
canton                          object
ventas_totales                   Int64
ventas_nacionales               object
exportaciones_netas             object
plazas_equiv                    object
plazas_equiv_hombres            object
plazas_equiv_mujeres            object
plazas                          object
plazas_hombres                  object
plazas_mujeres                  object
plazas_ult                      object
plazas_ult_hombres              object
plazas_ult_mujeres              object
plazas_iess_trim_1              object
plazas_iess_trim_2              object
plazas_iess_trim_3              object
plazas_iess_trim_4              object
plazas_rango_edad_1             object
plazas_rango_edad_2             object
plazas_rango_edad_3             object
plazas_rango_edad_4             object
plazas_rango_edad_5             object
plazas_ult_rango_edad_1         object
plazas_ult_rango_edad_2         object
plazas_ult_rango_edad_3         object
plazas_ult_rango_edad_4         object
plazas_ult_rango_edad_5         object
empleo_equiv                    object
empleo_equiv_hombres            object
empleo_equiv_mujeres            object
empleo                          object
empleo_hombres                  object
empleo_mujeres                  object
empleo_ult                      object
empleo_ult_hombres              object
empleo_ult_mujeres              object
empleo_iess_trim_1              object
empleo_iess_trim_2              object
empleo_iess_trim_3              object
empleo_iess_trim_4              object
empleo_rango_edad_1             object
empleo_rango_edad_2             object
empleo_rango_edad_3             object
empleo_rango_edad_4             object
empleo_rango_edad_5             object
empleo_ult_rango_edad_1         object
empleo_ult_rango_edad_2         object
empleo_ult_rango_edad_3         object
empleo_ult_rango_edad_4         object
empleo_ult_rango_edad_5         object
estrato_ventas                  object
estrato_plazase                 object
estrato_empleoe                 object
estrato_plazasp                 object
estrato_empleop                 object
estrato_plazasu                 object
estrato_empleou                 object
estrato_ventas_cop              object
estrato_plazas_cop              object
tamanoe_plazas                  object
tamanoe_empleo                  object
tamanop_plazas                  object
tamanop_empleo                  object
tamanou_plazas                  object
tamanou_empleo                  object
tamano_cop                      object
rimpe                           object
remuneraciones                  object
remuneraciones_hombres          object
remuneraciones_mujeres          object
estructura_estrat               object
propietarios_sexo               object
fecha_inicio_actividad          object
fecha_cese_actividad            object
fecha_reinicio_actividad        object
fecha_inscripcion               object
fecha_actualizacion             object
fecha_suspension_definitiva     object
dtype: object

In [21]:
raw_inec.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1246162 entries, 0 to 1246161
Data columns (total 96 columns):
 #   Column                        Non-Null Count    Dtype
---  ------                        --------------    -----
 0   id_empresa                    1246162 non-null  int64
 1   anio                          1246162 non-null  int64
 2   situacion                     1246162 non-null  object
 3   forma_institucional           1246162 non-null  object
 4   unidad_legal_tipo             1246162 non-null  object
 5   clase_contribuyente           1246162 non-null  object
 6   obligado_llevar_contabilidad  1246162 non-null  object
 7   gsectores                     1246162 non-null  object
 8   codigo_seccion                1246162 non-null  object
 9   seccion                       1246162 non-null  object
 10  codigo_division               1246162 non-null  object
 11  division                      1246162 non-null  object
 12  codigo_clase                  1246162 non-null  object
 13  clase                         1246162 non-null  object
 14  zona_planif                   1246162 non-null  object
 15  codigo_provincia              1246162 non-null  int64
 16  provincia                     1246162 non-null  object
 17  codigo_canton                 1246162 non-null  int64
 18  canton                        1246162 non-null  object
 19  ventas_totales                1246162 non-null  object
 20  ventas_nacionales             1246162 non-null  object
 21  exportaciones_netas           1246162 non-null  object
 22  plazas_equiv                  1246162 non-null  object
 23  plazas_equiv_hombres          1246162 non-null  object
 24  plazas_equiv_mujeres          1246162 non-null  object
 25  plazas                        1246162 non-null  object
 26  plazas_hombres                1246162 non-null  object
 27  plazas_mujeres                1246162 non-null  object
 28  plazas_ult                    1246162 non-null  object
 29  plazas_ult_hombres            1246162 non-null  object
 30  plazas_ult_mujeres            1246162 non-null  object
 31  plazas_iess_trim_1            1246162 non-null  object
 32  plazas_iess_trim_2            1246162 non-null  object
 33  plazas_iess_trim_3            1246162 non-null  object
 34  plazas_iess_trim_4            1246162 non-null  object
 35  plazas_rango_edad_1           1246162 non-null  object
 36  plazas_rango_edad_2           1246162 non-null  object
 37  plazas_rango_edad_3           1246162 non-null  object
 38  plazas_rango_edad_4           1246162 non-null  object
 39  plazas_rango_edad_5           1246162 non-null  object
 40  plazas_ult_rango_edad_1       1246162 non-null  object
 41  plazas_ult_rango_edad_2       1246162 non-null  object
 42  plazas_ult_rango_edad_3       1246162 non-null  object
 43  plazas_ult_rango_edad_4       1246162 non-null  object
 44  plazas_ult_rango_edad_5       1246162 non-null  object
 45  empleo_equiv                  1246162 non-null  object
 46  empleo_equiv_hombres          1246162 non-null  object
 47  empleo_equiv_mujeres          1246162 non-null  object
 48  empleo                        1246162 non-null  object
 49  empleo_hombres                1246162 non-null  object
 50  empleo_mujeres                1246162 non-null  object
 51  empleo_ult                    1246162 non-null  object
 52  empleo_ult_hombres            1246162 non-null  object
 53  empleo_ult_mujeres            1246162 non-null  object
 54  empleo_iess_trim_1            1246162 non-null  object
 55  empleo_iess_trim_2            1246162 non-null  object
 56  empleo_iess_trim_3            1246162 non-null  object
 57  empleo_iess_trim_4            1246162 non-null  object
 58  empleo_rango_edad_1           1246162 non-null  object
 59  empleo_rango_edad_2           1246162 non-null  object
 60  empleo_rango_edad_3           1246162 non-null  object
 61  empleo_rango_edad_4           1246162 non-null  object
 62  empleo_rango_edad_5           1246162 non-null  object
 63  empleo_ult_rango_edad_1       1246162 non-null  object
 64  empleo_ult_rango_edad_2       1246162 non-null  object
 65  empleo_ult_rango_edad_3       1246162 non-null  object
 66  empleo_ult_rango_edad_4       1246162 non-null  object
 67  empleo_ult_rango_edad_5       1246162 non-null  object
 68  estrato_ventas                1246162 non-null  object
 69  estrato_plazase               1246162 non-null  object
 70  estrato_empleoe               1246162 non-null  object
 71  estrato_plazasp               1246162 non-null  object
 72  estrato_empleop               1246162 non-null  object
 73  estrato_plazasu               1246162 non-null  object
 74  estrato_empleou               1246162 non-null  object
 75  estrato_ventas_cop            1246162 non-null  object
 76  estrato_plazas_cop            1246162 non-null  object
 77  tamanoe_plazas                1246162 non-null  object
 78  tamanoe_empleo                1246162 non-null  object
 79  tamanop_plazas                1246162 non-null  object
 80  tamanop_empleo                1246162 non-null  object
 81  tamanou_plazas                1246162 non-null  object
 82  tamanou_empleo                1246162 non-null  object
 83  tamano_cop                    1246162 non-null  object
 84  rimpe                         1246162 non-null  object
 85  remuneraciones                1246162 non-null  object
 86  remuneraciones_hombres        1246162 non-null  object
 87  remuneraciones_mujeres        1246162 non-null  object
 88  estructura_estrat             1246162 non-null  object
 89  propietarios_sexo             1246162 non-null  object
 90  fecha_inicio_actividad        1246162 non-null  object
 91  fecha_cese_actividad          1246162 non-null  object
 92  fecha_reinicio_actividad      1246162 non-null  object
 93  fecha_inscripcion             1246162 non-null  object
 94  fecha_actualizacion           1246162 non-null  object
 95  fecha_suspension_definitiva   1246162 non-null  object
dtypes: int64(4), object(92)
memory usage: 912.7+ MB

In [24]:
# Verificar los valores únicos en la columna 'Provincia'
print(raw_inec['gsectores'].unique())

['Comercio' 'Industrias Manufactureras' 'Servicios'
 'Agricultura, ganadería, silvicultura y pesca' 'Construcción'
 'Explotación de Minas y Canteras']

In [6]:
print(raw_inec['forma_institucional'].unique())

['Persona Natural obligado a llevar contabilidad'
 'Persona Natural no obligado a llevar contabilidad'
 'Sociedad con fines de lucro' 'Institución Pública'
 'Sociedad sin fines de lucro' 'Empresa Pública'
 'Economía Popular y Solidaria']

In [7]:
print(raw_inec['unidad_legal_tipo'].unique())

['Persona Natural' 'Persona Jurídica']

In [22]:
print(raw_inec['clase_contribuyente'].unique())

['Otro Contribuyente' 'Rimpe' 'Contribuyente Especial' 'No Aplica']

In [26]:
print(raw_inec['obligado_llevar_contabilidad'].unique())

['Si' 'No' 'No Aplica']

In [25]:
print(raw_inec['gsectores'].unique())

['Comercio' 'Industrias Manufactureras' 'Servicios'
 'Agricultura, ganadería, silvicultura y pesca' 'Construcción'
 'Explotación de Minas y Canteras']

In [27]:
print(raw_inec['seccion'].unique())

['Comercio, reparación automotores y motocicletas'
 'Industrias manufactureras' 'Enseñanza'
 'Actividades de alojamiento y de servicio de comidas'
 'Agricultura, ganadería,  silvicultura y pesca'
 'Actividades inmobiliarias'
 'Actividades de atención a la salud humana y asistencia social'
 'Actividades profesionales, científicas y técnicas'
 'Otras actividades de servicios'
 'Suministro electricidad, gas, vapor y aire acondicionado'
 'Información y comunicación' 'Actividades financieras y de seguros'
 'Transporte y almacenamiento' 'Construcción'
 'Actividades de servicios administrativos y de apoyo'
 'Artes, entretenimiento y recreación' 'Explotación minas y canteras'
 'Distribución agua; alcantarillado, desechos y saneamiento'
 'Administración pública y defensa, seguridad social']

In [28]:
print(raw_inec['division'].unique())

['Comercio al por menor, excepto el de vehículos automotores y motocicletas.'
 'Fabricación de productos elaborados de metal, excepto maquinaria y equipo.'
 'Comercio y reparación de vehículos automotores y motocicletas.'
 'Enseñanza.' 'Servicio de alimento y bebida.' 'Fabricación de muebles.'
 'Agricultura, ganadería, caza y actividades de servicios conexas'
 'Fabricación de equipo eléctrico.' 'Actividades inmobiliarias.'
 'Comercio al por mayor, excepto el de vehículos automotores y motocicletas.'
 'Producción de madera y fabricación de productos de madera y corcho, excepto muebles; fabricación de artículos de paj'
 'Impresión y reproducción de grabaciones.'
 'Fabricación de prendas de vestir.'
 'Fabricación de otros productos minerales no metálicos.'
 'Actividades de atención de la salud humana.'
 'Actividades de oficinas principales; actividades de consultoría de gestión.'
 'Actividades de alojamiento.'
 'Reparación e instalación de maquinaria y equipo.'
 'Otras actividades profesionales, científicas y técnicas.'
 'Fabricación de productos textiles.'
 'Otras actividades de servicios personales.'
 'Fabricación de vehículos automotores, remolques y semirremolques.'
 'Reparación de computadores y de efectos personales y enseres domésticos.'
 'Fabricación de papel y de productos de papel.'
 'Otras industrias manufactureras.'
 'Actividades de arquitectura e ingeniería; ensayos y análisis técnicos.'
 'Suministro de electricidad, gas, vapor y aire acondicionado.'
 'Actividades de programación y transmisión.'
 'Fabricación de productos de caucho y plástico.'
 'Actividades auxiliares de las actividades de servicios financieros.'
 'Transporte por vía terrestre y por tuberías.'
 'Actividades jurídicas y de contabilidad.'
 'Actividades especializadas de la construcción.'
 'Elaboración de productos alimenticios'
 'Actividades de alquiler y arrendamiento.'
 'Fabricación de cueros y productos conexos.'
 'Actividades administrativas y de apoyo de oficina y otras actividades de apoyo a las empresas.'
 'Actividades creativas, artísticas y de entretenimiento.'
 'Actividades de servicios de información.'
 'Actividades deportivas, de esparcimiento y recreativas.'
 'Construcción de edificios.' 'Fabricación de metales comunes.'
 'Extracción de minerales metalíferos'
 'Explotación de otras minas y canteras' 'Telecomunicaciones.'
 'Almacenamiento y actividades de apoyo al transporte.'
 'Publicidad y estudios de mercado.'
 'Fabricación de maquinaria y equipo n.c.p.'
 'Silvicultura y extracción de madera' 'Actividades de asociaciones.'
 'Obras de ingeniería civil.' 'Actividades postales y de mensajería.'
 'Recolección, tratamiento y eliminación de desechos, recuperación de materiales.'
 'Elaboración de bebidas'
 'Actividades de servicios a edificios y paisajismo.'
 'Actividades de empleo.'
 'Fabricación de productos de informática, electrónica y óptica.'
 'Actividades de asistencia social sin alojamiento.'
 'Actividades de publicación.' 'Actividades veterinarias.'
 'Investigación científica y desarrollo.'
 'Fabricación de substancias y productos químicos.'
 'Actividades de agencias de viajes, operadores turísticos, servicios de reservas y actividades conexas.'
 'Programación informática, consultoría de informática y actividades conexas.'
 'Actividades de atención en instituciones.' 'Pesca y acuicultura'
 'Actividades de producción de películas cinematográficas, vídeos y programas de televisión, grabación de sonido y e'
 'Actividades de seguridad e investigación.'
 'Actividades de bibliotecas, archivos, museos y otras actividades culturales.'
 'Actividades de servicios financieros, excepto las de seguros y fondos de pensiones.'
 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria.'
 'Captación, tratamiento y distribución de agua.'
 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico.'
 'Seguros, reaseguros y fondos de pensiones, excepto los planes de seguridad social de afiliación obligatoria.'
 'Actividades de juegos de azar y apuestas.'
 'Fabricación de coque y de productos de la refinación del petróleo.'
 'Transporte por vía acuática.'
 'Fabricación de otros tipos de equipos de transporte.'
 'Transporte por vía aérea.'
 'Actividades de descontaminación y otros servicios de  gestión de desechos.'
 'Evacuación de aguas residuales.'
 'Extracción de petróleo crudo y gas natural'
 'Extracción de carbón de piedra y lignito'
 'Actividades de servicios de apoyo para la explotación de minas y canteras'
 'Elaboración de productos de tabaco']

In [29]:
print(raw_inec['clase'].unique())

['Venta al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en comercios especiali'
 'Venta al por menor de otros productos nuevos en comercios especializados.'
 'Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados.'
 'Venta al por menor de prendas de vestir, calzado y artículos de cuero en comercios especializados.'
 'Fabricación de productos metálicos para uso estructural.'
 'Venta al por menor de artículos de ferretería, pinturas y productos de vidrio en comercios especializados.'
 'Mantenimiento y reparación de vehículos automotores.'
 'Enseñanza preprimaria y primaria.'
 'Actividades de restaurantes y de servicio móvil de comidas.'
 'Venta al por menor en comercios no especializados con predominio de la venta de alimentos, bebidas o tabaco.'
 'Fabricación de muebles.' 'Cría de ganado bovino y búfalos.'
 'Fabricación de aparatos de uso doméstico.'
 'Otras actividades de venta al por menor en comercios no especializados.'
 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrato.'
 'Venta al por mayor de materiales para la construcción, artículos de ferretería, equipo, materiales de fontanería (pl'
 'Fabricación de otros productos de madera; fabricación de artículos de corcho, paja y materiales trenzables.'
 'Actividades de impresión.'
 'Actividades inmobiliarias realizadas con bienes propios o arrendados.'
 'Fabricación de prendas de vestir, excepto prendas de piel.'
 'Fabricación de artículos de hormigón, de cemento y yeso.'
 'Actividades de médicos y odontólogos.'
 'Venta de partes, piezas y accesorios para vehículos automotores.'
 'Actividades de consultoría de gestión.'
 'Actividades de alojamiento para estancias cortas.'
 'Enseñanza de formación técnica y profesional.'
 'Reparación de maquinaria.'
 'Venta al por mayor de alimentos, bebidas y tabaco.'
 'Actividades de fotografía.'
 'Venta al por menor de otros productos en puestos de venta y mercados.'
 'Fabricación de tapices y alfombras.'
 'Actividades de peluquería y otros tratamientos de belleza.'
 'Venta al por menor de alimentos en comercios especializados.'
 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques.'
 'Reparación de calzado y artículos de cuero.'
 'Venta al por menor de tapices, alfombras y cubrimientos para paredes y pisos en comercios especializados.'
 'Fabricación de otros artículos del papel y cartón.'
 'Otras actividades de servicios personales n.c.p.'
 'Venta al por menor de grabaciones de música y de vídeo en comercios especializados.'
 'Tratamiento y revestimiento de metales; maquinado.'
 'Fabricación de instrumentos y materiales médicos y odontológicos.'
 'Actividades de arquitectura e ingeniería y actividades conexas de consultoría técnica.'
 'Venta al por menor de productos textiles en comercios especializados.'
 'Suministro de vapor y de aire acondicionado.'
 'Venta al por menor de computadores, equipo periférico, programas informáticos y equipo de telecomunicaciones en comerc'
 'Actividades de hospitales y clínicas.'
 'Cultivo de frutas tropicales y subtropicales.' 'Transmisiones de radio.'
 'Aserrado y acepilladura de madera.'
 'Fabricación de productos de plástico.'
 'Actividades de los agentes y corredores de seguro.'
 'Otras actividades de transporte de pasajeros por vía terrestre.'
 'Venta al por menor de bebidas en comercios especializados.'
 'Actividades de contabilidad, teneduría de libros y auditorias; consultoría fiscal.'
 'Forja, prensado, estampado y laminado de metales; pulvimetalurgia.'
 'Otras actividades profesionales, científicas y técnicas n.c.p.'
 'Venta al por menor de aparatos eléctricos de uso doméstico, muebles, equipo de iluminación y otros enseres doméstico'
 'Otras actividades de atención de la salud humana.'
 'Fabricación de partes y piezas de carpintería para edificios y construcciones.'
 'Fontanería (plomería, gasfitería) e instalación de calefacción y aire acondicionado.'
 'Actividades de servicios relacionados con la impresión.'
 'Elaboración de productos de molinería.'
 'Actividades de servicio de bebidas.'
 'Alquiler otros efectos personales y artículos de uso domésticos.'
 'Venta al por mayor de combustibles sólidos, líquidos y gaseosos y productos conexos.'
 'Cultivo de caña de azúcar.'
 'Venta al por menor de combustibles para vehículos automotores en comercios especializados.'
 'Pompas fúnebres y actividades conexas.'
 'Venta al por menor de alimentos, bebidas y tabaco en puestos de venta y mercados.'
 'Venta al por mayor de otros enseres domésticos.'
 'Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir.'
 'Fabricación de otros productos de porcelana y de cerámica.'
 'Fabricación de calzado.' 'Fabricación de joyas y artículos conexos.'
 'Otras industrias manufactureras n.c.p.'
 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo de oficina.'
 'Tejedura de productos textiles.'
 'Actividades creativas, artísticas y de entretenimiento.'
 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería.'
 'Venta al por mayor de maquinaria, equipo y materiales agropecuarios.'
 'Venta al por mayor de textiles, prendas de vestir y calzado.'
 'Elaboración de productos lácteos.'
 'Otras actividades especializadas de construcción.'
 'Actividades de agencias de noticias.'
 'Terminación y acabado de edificios.'
 'Transporte de carga por carretera.'
 'Explotación de instalaciones deportivas.'
 'Reparación de otros bienes personales y enseres domésticos.'
 'Venta al por mayor de materias primas agropecuarias y animales vivos.'
 'Venta, mantenimiento y reparación de motocicletas y de sus partes, piezas y accesorios.'
 'Actividades jurídicas.' 'Reparación de equipo eléctrico.'
 'Elaboración de productos de panadería.'
 'Reparación de aparatos de uso doméstico y equipo doméstico y de jardinería.'
 'Fabricación de productos refractarios.'
 'Alquiler de otros tipos de maquinaria, equipo y bienes tangibles.'
 'Corte, tallado y acabado de la piedra.'
 'Venta al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y mercados.'
 'Construcción de edificios.' 'Instalaciones eléctricas.'
 'Venta al por menor de equipo de deporte en comercios especializados.'
 'Fundición de metales no ferrosos.'
 'Extracción de otros minerales metalíferos no ferrosos.'
 'Extracción de piedra, arena y arcilla.'
 'Actividades de telecomunicaciones inalámbricas.'
 'Fabricación de productos primarios de metales preciosos y metales no ferrosos.'
 'Cría de otros animales.'
 'Venta al por mayor de desperdicios, desechos, chatarra y otros productos n.c.p.'
 'Fabricación de vidrio y productos de vidrio.'
 'Reparación de aparatos electrónicos de consumo.'
 'Fabricación de equipo eléctrico de iluminación.'
 'Transporte urbano y suburbano de pasajeros por vía terrestre.'
 'Otras actividades de telecomunicaciones.'
 'Otros tipos de enseñanza n.c.p.'
 'Venta al por mayor de otros tipos de maquinaria y equipo.'
 'Cultivo de frutos oleaginosos.'
 'Fabricación de maletas, bolsos de mano y artículos similares, artículos de talabartería y guarnicionería.'
 'Otras actividades de apoyo al transporte.' 'Publicidad.'
 'Fabricación de otros productos textiles n.c.p.'
 'Elaboración y conservación de frutas, legumbres y hortalizas.'
 'Fabricación de maquinaria agropecuaria y forestal.'
 'Enseñanza cultural.' 'Suministro de comidas por encargo.'
 'Silvicultura y otras actividades forestales.'
 'Reparación de equipo electrónico y óptico.'
 'Actividades de otras asociaciones n.c.p.'
 'Construcción de carreteras y líneas de ferrocarril.'
 'Venta al por menor de equipo de sonido y vídeo en comercios especializados.'
 'Reparación de muebles y accesorios domésticos.'
 'Fabricación de otros tipos de maquinaria de uso general.'
 'Organización de convenciones y exposiciones comerciales.'
 'Fabricación de recipientes de madera.'
 'Venta al por mayor de otros productos no especializado.'
 'Otras actividades de venta al por menor no realizadas en comercios, puestos de venta o mercados.'
 'Venta al por menor de artículos de segunda mano en comercios especializados.'
 'Actividades postales.'
 'Otras actividades de servicios de apoyo a empresas n.c.p.'
 'Fundición de hierro y acero.'
 'Fabricación de equipo de propulsión de fluidos.'
 'Recuperación de materiales.'
 'Elaboración de otros productos alimenticios n.c.p.'
 'Venta de vehículos automotores.' 'Elaboración y conservación de carne.'
 'Actividades de mensajería.'
 'Elaboración de bebidas no alcohólicas; producción de aguas minerales y otras aguas embotelladas.'
 'Industrias básicas de hierro y acero.'
 'Cultivo de productos agrícolas en combinación con la cría de animales (explotación mixta).'
 'Servicios de apoyo a la silvicultura.'
 'Otras actividades de servicio de comidas.'
 'Recolección de desechos peligrosos.'
 'Fabricación de partes, piezas y accesorios para vehículos automotores.'
 'Fabricación de materiales de construcción de arcilla.'
 'Limpieza general de edificios.' 'Actividades de agencias de empleo.'
 'Fabricación de relojes.' 'Venta al por menor por correo y por internet.'
 'Otras actividades de asistencia social sin alojamiento.'
 'Generación, transmisión y distribución de energía eléctrica.'
 'Lavado y limpieza, incluida la limpieza en seco, de productos textiles y de piel.'
 'Actividades especializadas de diseño.'
 'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción.'
 'Fabricación de motores, generadores, transformadores eléctricos y aparatos de distribución y control de la energía e'
 'Instalación de maquinaria y equipo industriales.'
 'Fabricación de otros productos de caucho.'
 'Fabricación de otros productos elaborados de metal n.c.p.'
 'Publicación de periódicos, diarios y revistas.'
 'Actividades veterinarias.' 'Enseñanza superior.'
 'Construcción de proyectos de servicios públicos.'
 'Otras actividades de esparcimiento y recreativas n.c.p.'
 'Actividades combinadas de servicios administrativos de oficina.'
 'Servicio de acabado de productos textiles.'
 'Fabricación de bisutería y artículos conexos.'
 'Actividades de campamentos, parques de vehículos de recreo y parques de caravanas.'
 'Reparación de computadoras y equipo periférico.'
 'Reparación de equipo de comunicaciones.'
 'Fabricación de maquinaria para la conformación de metales y de máquinas herramienta.'
 'Venta al por mayor de metales y minerales metalíferos.'
 'Almacenamiento y depósito.'
 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades.'
 'Elaboración de cacao, chocolate y productos de confitería.'
 'Fabricación de otros productos químicos n.c.p.'
 'Venta al por mayor de computadoras, equipo y programas informáticos.'
 'Otras actividades deportivas.'
 'Construcción de otras obras de ingeniería civil.'
 'Actividades de paisajismo y servicios de mantenimiento conexos.'
 'Actividades de servicios vinculadas al transporte terrestre.'
 'Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador.'
 'Venta al por menor de juegos y juguetes en comercios especializados.'
 'Alquiler de cintas de video y discos.'
 'Fabricación de plásticos y cauchos sintéticos en formas primarias.'
 'Fabricación de tejidos de punto y ganchillo.'
 'Actividades combinadas de apoyo a instalaciones.'
 'Fabricación de maquinaria metalúrgica.'
 'Otros servicios de reservas y actividades conexas.'
 'Fabricación de otros productos minerales no metálicos n.c.p.'
 'Actividades de telecomunicaciones alámbrica.'
 'Actividades de agencias de empleo temporal.'
 'Actividades de consultoría de informática y de gestión de instalaciones informáticas.'
 'Otras actividades de servicios de información n.c.p.'
 'Actividades de agencias de cobro y agencias de calificación crediticia.'
 'Actividades de atención de enfermería en instituciones.'
 'Actividades de atención en instituciones para personas de edad y personas con discapacidad.'
 'Alquiler de equipo recreativo y deportivo.'
 'Fabricación de herramientas de mano motorizadas.'
 'Fabricación de equipo de elevación y manipulación.'
 'Cultivo de otras plantas perennes.' 'Fabricación de artículos de piel.'
 'Cría de aves de corral.'
 'Otras actividades auxiliares a las actividades de servicios financieros.'
 'Reproducción de grabaciones.'
 'Actividades de telecomunicaciones por satélite.'
 'Fabricación de cemento, cal y yeso.' 'Cría de ovejas y cabras.'
 'Acuicultura marina.'
 'Actividades de atención en instituciones para personas con retraso mental, enfermos mentales y toxicómanos.'
 'Actividades de producción de películas cinematográficas, vídeos y programas de televisión.'
 'Enseñanza deportiva y recreativa.'
 'Elaboración de comidas y platos preparados.'
 'Actividades de seguridad privada.'
 'Recolección de desechos no peligrosos.'
 'Actividades de agencias de viajes.'
 'Actividades de grabación de sonido y edición de música.'
 'Programación y transmisiones de televisión.'
 'Actividades de programación informática.'
 'Actividades de jardines botánicos y zoológicos y reservas naturales.'
 'Venta al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones.'
 'Preparación e hilatura de fibras textiles.' 'Banca central.'
 'Fabricación de equipo de comunicaciones.'
 'Otras actividades de tecnología de la información y de servicios informáticos.'
 'Propagación de plantas.'
 'Fabricación de otros tipos de maquinaria de uso especial.'
 'Elaboración de alimentos preparados para animales.'
 'Actividades de parques de atracciones y parques temáticos.'
 'Otras actividades de limpieza de edificios e instalaciones industriales.'
 'Actividades de la administración pública en general.'
 'Regulación de las actividades de organismos que prestan servicios sanitarios, educativos, culturales y otros servicios'
 'Actividades de mantenimiento del orden público y de seguridad.'
 'Otras actividades de atención en instituciones.'
 'Actividades de defensa.'
 'Actividades de museos y gestión de lugares y edificios históricos.'
 'Captación, tratamiento y distribución de agua.'
 'Destilación, rectificación y mezcla de bebidas alcohólicas.'
 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares.'
 'Curtido y adobo de cueros; adobo y teñido de pieles.'
 'Fabricación de cubiertas y cámaras de caucho; recauchutado y renovación de cubiertas de caucho.'
 'Otros tipos de intermediación monetaria.'
 'Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas.'
 'Enseñanza secundaria de formación general.'
 'Actividades de organizaciones religiosas.' 'Actividades de sindicatos.'
 'Elaboración de vinos.' 'Fabricación de juegos y juguetes.'
 'Fabricación de substancias químicas básicas.'
 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico.'
 'Actividades de asociaciones empresariales y de empleadores.'
 'Fabricación de papel y cartón ondulado y de envases de papel y cartón.'
 'Actividades de clubes deportivos.'
 'Actividades de asociaciones profesionales.'
 'Fabricación de otros tipos de equipo eléctrico.' 'Seguros generales.'
 'Fabricación de pasta de madera, papel y cartón.'
 'Cultivo de otras plantas no perennes.'
 'Actividades de asistencia social sin alojamiento para personas de edad y personas con discapacidad.'
 'Estudios de mercado y encuestas de opinión pública.'
 'Actividades de servicios de sistemas de seguridad.'
 'Preparación del terreno.'
 'Fabricación de componentes y tableros electrónicos.'
 'Venta al por mayor a cambio de una comisión o por contrato.'
 'Actividades de operadores turísticos.'
 'Actividades de apoyo a la enseñanza.'
 'Fabricación de abonos y compuestos de nitrógeno.'
 'Actividades de servicios vinculadas al transporte aéreo.'
 'Alquiler de vehículos automotores.'
 'Fabricación de aparatos electrónicos de consumo.'
 'Fabricación de artículos de deporte.' 'Cultivo de arroz.'
 'Actividades de oficinas principales.'
 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario.'
 'Cultivo de otros frutos y nueces de árboles y arbustos.'
 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas.'
 'Actividades de juegos de azar y apuestas.'
 'Fabricación de hornos y quemadores.'
 'Regulación y facilitación de la actividad económica.'
 'Fabricación de productos de horno de coque.'
 'Reparación de productos elaborados de metal.'
 'Cultivo de plantas con las que se preparan bebidas.'
 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros.'
 'Fabricación de artículos de punto y ganchillo.' 'Elaboración de azúcar.'
 'Fabricación de vehículos automotores.'
 'Cultivo de hortalizas y melones, raíces y tubérculos.'
 'Actividades poscosecha.' 'Fabricación de instrumentos musicales.'
 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión.'
 'Procesamiento de datos, hospedaje y actividades conexas.'
 'Otras publicaciones.' 'Manipulación de carga.'
 'Fabricación de tanques, depósitos y recipientes de metal.'
 'Actividades de apoyo a la agricultura.'
 'Publicación de libros, periódicos y otras actividades de publicación.'
 'Acuicultura de agua dulce.'
 'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas.'
 'Actividades de bibliotecas y archivos.'
 'Fabricación de hojas de madera para enchapado y tableros a base de madera.'
 'Otras actividades de alojamiento.' 'Cultivo de cítricos.'
 'Actividades de envasado y empaquetado.'
 'Fabricación de equipos de medición, prueba, navegación, control y de relojes.'
 'Extracción de minerales de uranio y torio.'
 'Elaboración de aceites y grasas de origen vegetal y animal.'
 'Actividades de apoyo a la ganadería.'
 'Tratamiento de semillas para propagación.' 'Extracción de madera.'
 'Fabricación de otras bombas, compresores, grifos y válvulas.'
 'Actividades de postproducción de películas cinematográficas, vídeos y programas de televisión.'
 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central.'
 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco.'
 'Otras actividades de dotación de recursos humanos.'
 'Actividades de centros de llamadas.' 'Evaluación de riesgos y daños.'
 'Reparación de equipo de transporte, excepto vehículos automotores.'
 'Caza ordinaria, mediante trampas y actividades de servicios conexas.'
 'Transporte de carga marítimo y de cabotaje.'
 'Construcción de embarcaciones de recreo y deporte.'
 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería.'
 'Pesca de agua dulce.' 'Cría de cerdos.'
 'Construcción de buques y estructuras flotantes.'
 'Publicación de programas informáticos.'
 'Actividades de servicios vinculadas al transporte acuático.'
 'Elaboración y conservación de pescados, crustáceos y moluscos.'
 'Fabricación de instrumentos ópticos y equipo fotográficos.'
 'Transporte de pasajeros marítimo y de cabotaje.'
 'Fabricación de bicicletas y de sillas de ruedas para inválidos.'
 'Pesca marina.' 'Portales web.'
 'Fabricación de gas; distribución de combustibles gaseosos por tuberías.'
 'Fondos y sociedades de inversión y entidades financieras similares.'
 'Fabricación de productos de la refinación del petróleo.'
 'Elaboración de bebidas malteadas y de malta.' 'Seguros de vida.'
 'Transporte de pasajeros por vía aérea.' 'Cultivo de tabaco.'
 'Administración de mercados financieros.'
 'Fabricación de cuerdas, cordeles, bramantes y redes.'
 'Otras actividades de concesión de crédito.'
 'Fabricación de pilas, baterías y acumuladores.'
 'Fabricación de otros hilos y cables eléctricos.'
 'Transporte de carga por vía aérea.' 'Ensayos y análisis técnicos.'

In [31]:
print(raw_inec['zona_planif'].unique())

['Zona 5 - Santa Elena, Guayas, Los Ríos, Bolívar, Galápagos'
 'Zona 6 - Azuay, Cañar, Morona Santiago'
 'Zona 9 - Quito Distrito Metropolitano'
 'Zona 3 - Cotopaxi, Tungurahua, Chimborazo, Pastaza'
 'Zona 7 - El Oro, Loja, Zamora Chinchipe'
 'Zona 8 - Guayaquil, Durán, Samborondón'
 'Zona 4 - Manabí, Santo Domingo de los Tsáchilas'
 'Zona 1 - Esmeraldas, Carchi, Imbabura, Sucumbíos'
 'Zona 2 - Pichincha, Napo, Orellana' 'Zona 90 - Zona no Delimitada']

In [8]:
(
    raw_inec
    .dtypes
    .value_counts()
)

object    92
int64      4
Name: count, dtype: int64

In [9]:
raw_inec.shape

(1246162, 96)

Valores nulos

In [32]:
(
    raw_inec
    .isnull()
    .any()
)

id_empresa                      False
anio                            False
situacion                       False
forma_institucional             False
unidad_legal_tipo               False
clase_contribuyente             False
obligado_llevar_contabilidad    False
gsectores                       False
codigo_seccion                  False
seccion                         False
codigo_division                 False
division                        False
codigo_clase                    False
clase                           False
zona_planif                     False
codigo_provincia                False
provincia                       False
codigo_canton                   False
canton                          False
ventas_totales                  False
ventas_nacionales               False
exportaciones_netas             False
plazas_equiv                    False
plazas_equiv_hombres            False
plazas_equiv_mujeres            False
plazas                          False
plazas_hombres                  False
plazas_mujeres                  False
plazas_ult                      False
plazas_ult_hombres              False
plazas_ult_mujeres              False
plazas_iess_trim_1              False
plazas_iess_trim_2              False
plazas_iess_trim_3              False
plazas_iess_trim_4              False
plazas_rango_edad_1             False
plazas_rango_edad_2             False
plazas_rango_edad_3             False
plazas_rango_edad_4             False
plazas_rango_edad_5             False
plazas_ult_rango_edad_1         False
plazas_ult_rango_edad_2         False
plazas_ult_rango_edad_3         False
plazas_ult_rango_edad_4         False
plazas_ult_rango_edad_5         False
empleo_equiv                    False
empleo_equiv_hombres            False
empleo_equiv_mujeres            False
empleo                          False
empleo_hombres                  False
empleo_mujeres                  False
empleo_ult                      False
empleo_ult_hombres              False
empleo_ult_mujeres              False
empleo_iess_trim_1              False
empleo_iess_trim_2              False
empleo_iess_trim_3              False
empleo_iess_trim_4              False
empleo_rango_edad_1             False
empleo_rango_edad_2             False
empleo_rango_edad_3             False
empleo_rango_edad_4             False
empleo_rango_edad_5             False
empleo_ult_rango_edad_1         False
empleo_ult_rango_edad_2         False
empleo_ult_rango_edad_3         False
empleo_ult_rango_edad_4         False
empleo_ult_rango_edad_5         False
estrato_ventas                  False
estrato_plazase                 False
estrato_empleoe                 False
estrato_plazasp                 False
estrato_empleop                 False
estrato_plazasu                 False
estrato_empleou                 False
estrato_ventas_cop              False
estrato_plazas_cop              False
tamanoe_plazas                  False
tamanoe_empleo                  False
tamanop_plazas                  False
tamanop_empleo                  False
tamanou_plazas                  False
tamanou_empleo                  False
tamano_cop                      False
rimpe                           False
remuneraciones                  False
remuneraciones_hombres          False
remuneraciones_mujeres          False
estructura_estrat               False
propietarios_sexo               False
fecha_inicio_actividad          False
fecha_cese_actividad            False
fecha_reinicio_actividad        False
fecha_inscripcion               False
fecha_actualizacion             False
fecha_suspension_definitiva     False
dtype: bool

In [11]:
(
    raw_inec
    .isnull()
    .sum()
)

id_empresa                     0
anio                           0
situacion                      0
forma_institucional            0
unidad_legal_tipo              0
                              ..
fecha_cese_actividad           0
fecha_reinicio_actividad       0
fecha_inscripcion              0
fecha_actualizacion            0
fecha_suspension_definitiva    0
Length: 96, dtype: int64

In [12]:
(
    raw_inec
    .isnull()
    .sum()
    .sum()
)

0

Conteos y porporciones

In [13]:
raw_inec.describe(include="all")

,id_empresa,anio,situacion,forma_institucional,unidad_legal_tipo,clase_contribuyente,obligado_llevar_contabilidad,gsectores,codigo_seccion,seccion,...,remuneraciones_hombres,remuneraciones_mujeres,estructura_estrat,propietarios_sexo,fecha_inicio_actividad,fecha_cese_actividad,fecha_reinicio_actividad,fecha_inscripcion,fecha_actualizacion,fecha_suspension_definitiva
count,1.246162e+06,1246162.0,1246162,1246162,1246162,1246162,1246162,1246162,1246162,1246162,...,1246162,1246162,1246162,1246162,1246162,1246162,1246162,1246162,1246162,1246162
unique,NaN,NaN,1,7,2,4,3,6,19,19,...,99197,78256,5,3,552,215,182,487,109,252
top,NaN,NaN,Activo,Persona Natural no obligado a llevar contabilidad,Persona Natural,Rimpe,No,Servicios,G,"Comercio, reparación automotores y motocicletas",...,,,RIMPE 2022,Hombres,2022 IV Trimestre,,,2022 IV Trimestre,2023 IV Trimestre,
freq,NaN,NaN,1246162,1044963,1077614,682800,1044963,612242,447256,447256,...,881392,932676,679558,567552,31097,1021047,802602,32030,259975,853560
mean,4.193494e+10,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.136616e+10,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.358247e+10,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,4.277238e+10,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,4.655639e+10,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,4.903644e+10,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,5.045451e+10,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
raw_inec.describe(include=[np.number])

         id_empresa       anio  codigo_provincia  codigo_canton
count  1.246162e+06  1246162.0      1.246162e+06   1.246162e+06
mean   4.193494e+10     2023.0      1.221450e+01   1.224317e+03
std    1.136616e+10        0.0      5.692569e+00   5.687704e+02
min    1.358247e+10     2023.0      1.000000e+00   1.010000e+02
25%    4.277238e+10     2023.0      9.000000e+00   9.010000e+02
50%    4.655639e+10     2023.0      1.200000e+01   1.205000e+03
75%    4.903644e+10     2023.0      1.700000e+01   1.701000e+03
max    5.045451e+10     2023.0      9.000000e+01   9.004000e+03

In [16]:
raw_inec.describe(include=object)

,situacion,forma_institucional,unidad_legal_tipo,clase_contribuyente,obligado_llevar_contabilidad,gsectores,codigo_seccion,seccion,codigo_division,division,...,remuneraciones_hombres,remuneraciones_mujeres,estructura_estrat,propietarios_sexo,fecha_inicio_actividad,fecha_cese_actividad,fecha_reinicio_actividad,fecha_inscripcion,fecha_actualizacion,fecha_suspension_definitiva
count,1246162,1246162,1246162,1246162,1246162,1246162,1246162,1246162,1246162,1246162,...,1246162,1246162,1246162,1246162,1246162,1246162,1246162,1246162,1246162,1246162
unique,1,7,2,4,3,6,19,19,85,85,...,99197,78256,5,3,552,215,182,487,109,252
top,Activo,Persona Natural no obligado a llevar contabilidad,Persona Natural,Rimpe,No,Servicios,G,"Comercio, reparación automotores y motocicletas",G47,"Comercio al por menor, excepto el de vehículos...",...,,,RIMPE 2022,Hombres,2022 IV Trimestre,,,2022 IV Trimestre,2023 IV Trimestre,
freq,1246162,1044963,1077614,682800,1044963,612242,447256,447256,332009,332009,...,881392,932676,679558,567552,31097,1021047,802602,32030,259975,853560

In [4]:
stats_categories = raw_inec.describe(include=object)
stats_categories.to_excel('cat_empresas_2023.xlsx', index=False)